#!/usr/bin/env bash

# Direktori tema dan konfigurasi
DIR="$HOME/suckless/dwm"
RASI="$DIR/rofi/powermenu.rasi"
CNFR="$DIR/rofi/confirm.rasi"

# Informasi tampilan
prompt="$(hostname) ($(echo $DESKTOP_SESSION))"
mesg="Uptime : $(uptime -p | sed -e 's/up //g')"

# Cek ikon pada tema utama
layout=$(grep 'USE_ICON' "$RASI" | cut -d'=' -f2 | tr -d '[:space:]')
layout=${layout:-NO}

# Pilihan menu berdasarkan ikon
if [[ "$layout" == 'NO' ]]; then
    option_1=" Lock"
    option_2=" Logout"
    option_3=" Suspend"
    option_4=" Hibernate"
    option_5=" Reboot"
    option_6=" Shutdown"
else
    option_1=""
    option_2=""
    option_3=""
    option_4=""
    option_5=""
    option_6=""
fi

# Cek ikon pada menu konfirmasi
cnflayout=$(grep 'USE_ICON' "$CNFR" | cut -d'=' -f2 | tr -d '[:space:]')
cnflayout=${cnflayout:-NO}

if [[ "$cnflayout" == 'NO' ]]; then
    yes=' Yes'
    no=' No'
else
    yes=''
    no=''
fi

# Fungsi untuk memanggil rofi
rofi_cmd() {
    rofi -dmenu \
        -p "$prompt" \
        -mesg "$mesg" \
        -markup-rows \
        -theme "$RASI"
}

# Jalankan rofi untuk memilih aksi
run_rofi() {
    echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Menu konfirmasi
confirm_cmd() {
    rofi -dmenu \
        -p 'Confirmation' \
        -mesg 'Are you sure?' \
        -selected-row 1 \
        -no-click-to-exit \
        -theme "$CNFR"
}

# Tampilkan konfirmasi
confirm_exit() {
    echo -e "$yes\n$no" | confirm_cmd
}

# Konfirmasi dan eksekusi
confirm_run () {
    selected="$(confirm_exit)"
    if [[ "$selected" == "$yes" ]]; then
        for cmd in "$@"; do
            [[ -n "$cmd" ]] && eval "$cmd"
        done
    else
        exit
    fi
}

# Jalankan perintah berdasarkan pilihan
run_cmd() {
    case "$1" in
        --opt1)
            # Kunci layar - pastikan kamu punya 'slock' atau ganti ke 'xsecurelock', dll.
            slock
            ;;
        --opt2)
            confirm_run "pkill -KILL -u $(whoami)"
            ;;
        --opt3)
            confirm_run "mpc -q pause" "amixer set Master mute" "sudo zzz"
            ;;
        --opt4)
            confirm_run "sudo zzz -Z"
            ;;
        --opt5)
            confirm_run "sudo reboot"
            ;;
        --opt6)
            confirm_run "sudo poweroff"
            ;;
    esac
}

# Jalankan menu
chosen="$(run_rofi)"
[ -z "$chosen" ] && exit

# Eksekusi berdasarkan pilihan
case "$chosen" in
    "$option_1") run_cmd --opt1 ;;
    "$option_2") run_cmd --opt2 ;;
    "$option_3") run_cmd --opt3 ;;
    "$option_4") run_cmd --opt4 ;;
    "$option_5") run_cmd --opt5 ;;
    "$option_6") run_cmd --opt6 ;;
esac
